### ISSUE TITLE
Investigate harvester stuck

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/harvester#11]
Probably due to EPMC client paging

E.g. http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=ISSN:%221553-7390%22%20OPEN_ACCESS:%22y%22%20UPDATE_DATE:2013-03-22%20sort_date:%22y%22&resulttype=core&format=json&page=33557&pageSize=1000

Then the logs indicate that `page` just keeps going up. Maybe EPMC changed how their REST search API works. The response does contain `nextCursorMark`, maybe we need to use that instead.

**Comment by emanuil-tolev** [comment]
May need a fix to the octopus EPMC client.

**Comment by richard-jones** [comment]
@Steven-Eardley - was this one fixed by your update to octopus?

**Comment by Steven-Eardley** [comment]
Yes, it's paging through using the cursor now.
